imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
#    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale: %locale%
    session:
        cookie_lifetime:   3600
        cookie_path:       \
        cookie_domain:     example.com
        cookie_secure:     true
        cookie_httponly:   true


# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_all_services: false

#monolog:
#    handlers:
#        mail:
#            type:         fingers_crossed
#            action_level: debug
#            handler:      buffered
#        buffered:
#            type:    buffer
#            handler: swift
#        swift:
#            type:       swift_mailer
#            from_email: error@mage-hackathon.de
#            to_email:   magehackathonerror@fabian-blechschmidt.de
#            subject:    Mage-Hackathon: ERROR
#            level:      debug

# PaypalIpnBundle Configuration
orderly_pay_pal_ipn:

    # If set to false then service loads settings with "sandbox_" prefix
    islive:  false

    # Constants for the live environment (default settings in Configuration.php)
    email:   %paypal_live_email%
    url:     https://www.paypal.com/cgi-bin/webscr
    debug:   %kernel.debug%

    # Constants for the sandbox environment (default settings in Configuration.php)
    sandbox_email:   %paypal_dev_email%
    sandbox_url:     https://www.sandbox.paypal.com/cgi-bin/webscr
    sandbox_debug:   true

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: ::knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default


services:
    magento_hackathon_registration.menu_builder:
        class: MagentoHackathon\RegistrationBundle\Menu\MenuBuilder
        arguments: [@knp_menu.factory,  @doctrine.orm.entity_manager]

    magento_hackathon_registration.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: magento_hackathon_registration.menu_builder
        factory_method: createMainMenu
        arguments: [@request]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

eko_feed:
    feeds:
        events:
            title:       'Magento Hackathon Community Events'
            description: 'Upcoming Events'
            link:        'http://www.magento-hackathon.de/'
            encoding:    'utf-8'
            author:      'Mage-Hackathon' # Only required for Atom feeds
