MagentoHackathonRegistrationBundle:
    resource: "@MagentoHackathonRegistrationBundle/Resources/config/routing.yml"
    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: MagentoHackathonRegistrationBundle:Default:index }

_event_about:
  pattern: /event/{eventId}/about
  defaults: { _controller: MagentoHackathonRegistrationBundle:Default:eventAbout }

_imprint:
    pattern:  /imprint
    defaults: { _controller: MagentoHackathonRegistrationBundle:Default:imprint }

_about:
    pattern:  /about
    defaults: { _controller: MagentoHackathonRegistrationBundle:Default:about }

_registration:
    pattern:  /register
    defaults: { _controller: MagentoHackathonRegistrationBundle:Register:index }

_thanks:
    pattern:  /register/thanks/{userId}
    defaults: { _controller: MagentoHackathonRegistrationBundle:Register:thanks, userId: null }

_ipn:
  pattern:  /ipn
  defaults:  { _controller: MagentoHackathonRegistrationBundle:Register:ipn }

_projectIdea:
  pattern:  /projectIdea
  defaults:  { _controller: MagentoHackathonRegistrationBundle:ProjectIdea:index }

_projectIdeaAll:
  pattern:  /projectIdea/all
  defaults:  { _controller: MagentoHackathonRegistrationBundle:ProjectIdea:all }

_atom:
  pattern:  /atomFeed
  defaults:  { _controller: MagentoHackathonRegistrationBundle:Default:atomFeed }

_rss:
  pattern:  /rssFeed
  defaults:  { _controller: MagentoHackathonRegistrationBundle:Default:rssFeed }
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
