parameters:
#    magento_hackathon_registration.example.class: MagentoHackathon\RegistrationBundle\Example

services:
#    magento_hackathon_registration.example:
#        class: %magento_hackathon_registration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
