MagentoHackathon\RegistrationBundle\Entity\User:
  properties:
    firstname:
      - NotBlank: ~
      - MaxLength: 63
    lastname:
      - NotBlank: ~
      - MaxLength: 63
    mail:
      - NotBlank: ~
      - Email: ~
      - MaxLength: 255
    address:
      - NotBlank: ~
      - MaxLength: 127
    zip:
      - NotBlank: ~
      - MaxLength: 15
    city:
      - NotBlank: ~
      - MaxLength: 31
    country:
      - NotBlank: ~
      - MaxLength: 3
      - Country: ~
    githubId:
      - MaxLength: 255
    additionalInfos: []
    memo: []
    event:
      - NotBlank: ~

  getters:
    eventLegal:
      - "True": { message: "You have to choose an event to register for!" }

MagentoHackathon\RegistrationBundle\Entity\ProjectIdea:
  properties:
      name:
        - NotBlank: ~
        - MaxLength: 255
      description:
        - NotBlank: ~
        - MaxLength: 4294967296
      author:
        - NotBlank: ~
        - MaxLength: 255